//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/Scripts/Input/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Camera"",
            ""id"": ""85dedbd7-60d0-4d40-9502-012ca6263f1f"",
            ""actions"": [
                {
                    ""name"": ""Delta"",
                    ""type"": ""PassThrough"",
                    ""id"": ""90e215eb-1418-4e92-ba5c-5e81f4b48b73"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drag"",
                    ""type"": ""Button"",
                    ""id"": ""2657f348-3a55-4e93-a494-5401a4aea842"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Turn"",
                    ""type"": ""Button"",
                    ""id"": ""1be0bab2-07e6-42d0-8202-f2e6cdc40aa1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""PassThrough"",
                    ""id"": ""acbac2ee-d446-4d9e-af91-1e34040b34a8"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b6f681ef-c2d0-4610-93ec-ee210130cbb5"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3b03f04-16b1-42d9-a574-323556801a5f"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99815935-bc48-4cb7-ba43-826ee3336aad"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb1d41a1-96e0-48c9-af63-57a859b3525e"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MemberAction"",
            ""id"": ""dfabe36c-fb2d-45bb-a47b-32888276fc6a"",
            ""actions"": [
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""fca7ff70-4018-46dd-9378-15431c5c8872"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DisableRun"",
                    ""type"": ""Button"",
                    ""id"": ""2c7dd204-ad82-49ca-9f3d-94b34a891f48"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableRun"",
                    ""type"": ""Button"",
                    ""id"": ""3155c688-a1e1-4cbf-8e54-8f4cbef9b31c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap(tapDelay=0.3)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""93314583-f917-4bc8-a730-c66b3d6f5f67"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfcb23a0-5f11-4dc2-a729-c402e2b9e284"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1561a508-2c9b-4042-8c93-ee0ab1b67fa1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DisableRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""StateAction"",
            ""id"": ""030191a0-a08a-453b-8899-ff4a7d209690"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""6a321b27-f359-4a1a-ab92-53a6c58ecc09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1896b257-79d2-4f44-8379-b7e518dea3c2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""6d18b041-6f47-4ddf-a59e-ec430e30c1ba"",
            ""actions"": [],
            ""bindings"": []
        }
    ],
    ""controlSchemes"": []
}");
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_Delta = m_Camera.FindAction("Delta", throwIfNotFound: true);
        m_Camera_Drag = m_Camera.FindAction("Drag", throwIfNotFound: true);
        m_Camera_Turn = m_Camera.FindAction("Turn", throwIfNotFound: true);
        m_Camera_Zoom = m_Camera.FindAction("Zoom", throwIfNotFound: true);
        // MemberAction
        m_MemberAction = asset.FindActionMap("MemberAction", throwIfNotFound: true);
        m_MemberAction_Crouch = m_MemberAction.FindAction("Crouch", throwIfNotFound: true);
        m_MemberAction_DisableRun = m_MemberAction.FindAction("DisableRun", throwIfNotFound: true);
        m_MemberAction_EnableRun = m_MemberAction.FindAction("EnableRun", throwIfNotFound: true);
        // StateAction
        m_StateAction = asset.FindActionMap("StateAction", throwIfNotFound: true);
        m_StateAction_Pause = m_StateAction.FindAction("Pause", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Camera
    private readonly InputActionMap m_Camera;
    private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
    private readonly InputAction m_Camera_Delta;
    private readonly InputAction m_Camera_Drag;
    private readonly InputAction m_Camera_Turn;
    private readonly InputAction m_Camera_Zoom;
    public struct CameraActions
    {
        private @PlayerInputs m_Wrapper;
        public CameraActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Delta => m_Wrapper.m_Camera_Delta;
        public InputAction @Drag => m_Wrapper.m_Camera_Drag;
        public InputAction @Turn => m_Wrapper.m_Camera_Turn;
        public InputAction @Zoom => m_Wrapper.m_Camera_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void AddCallbacks(ICameraActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
            @Delta.started += instance.OnDelta;
            @Delta.performed += instance.OnDelta;
            @Delta.canceled += instance.OnDelta;
            @Drag.started += instance.OnDrag;
            @Drag.performed += instance.OnDrag;
            @Drag.canceled += instance.OnDrag;
            @Turn.started += instance.OnTurn;
            @Turn.performed += instance.OnTurn;
            @Turn.canceled += instance.OnTurn;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
        }

        private void UnregisterCallbacks(ICameraActions instance)
        {
            @Delta.started -= instance.OnDelta;
            @Delta.performed -= instance.OnDelta;
            @Delta.canceled -= instance.OnDelta;
            @Drag.started -= instance.OnDrag;
            @Drag.performed -= instance.OnDrag;
            @Drag.canceled -= instance.OnDrag;
            @Turn.started -= instance.OnTurn;
            @Turn.performed -= instance.OnTurn;
            @Turn.canceled -= instance.OnTurn;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
        }

        public void RemoveCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraActions @Camera => new CameraActions(this);

    // MemberAction
    private readonly InputActionMap m_MemberAction;
    private List<IMemberActionActions> m_MemberActionActionsCallbackInterfaces = new List<IMemberActionActions>();
    private readonly InputAction m_MemberAction_Crouch;
    private readonly InputAction m_MemberAction_DisableRun;
    private readonly InputAction m_MemberAction_EnableRun;
    public struct MemberActionActions
    {
        private @PlayerInputs m_Wrapper;
        public MemberActionActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Crouch => m_Wrapper.m_MemberAction_Crouch;
        public InputAction @DisableRun => m_Wrapper.m_MemberAction_DisableRun;
        public InputAction @EnableRun => m_Wrapper.m_MemberAction_EnableRun;
        public InputActionMap Get() { return m_Wrapper.m_MemberAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MemberActionActions set) { return set.Get(); }
        public void AddCallbacks(IMemberActionActions instance)
        {
            if (instance == null || m_Wrapper.m_MemberActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MemberActionActionsCallbackInterfaces.Add(instance);
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @DisableRun.started += instance.OnDisableRun;
            @DisableRun.performed += instance.OnDisableRun;
            @DisableRun.canceled += instance.OnDisableRun;
            @EnableRun.started += instance.OnEnableRun;
            @EnableRun.performed += instance.OnEnableRun;
            @EnableRun.canceled += instance.OnEnableRun;
        }

        private void UnregisterCallbacks(IMemberActionActions instance)
        {
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @DisableRun.started -= instance.OnDisableRun;
            @DisableRun.performed -= instance.OnDisableRun;
            @DisableRun.canceled -= instance.OnDisableRun;
            @EnableRun.started -= instance.OnEnableRun;
            @EnableRun.performed -= instance.OnEnableRun;
            @EnableRun.canceled -= instance.OnEnableRun;
        }

        public void RemoveCallbacks(IMemberActionActions instance)
        {
            if (m_Wrapper.m_MemberActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMemberActionActions instance)
        {
            foreach (var item in m_Wrapper.m_MemberActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MemberActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MemberActionActions @MemberAction => new MemberActionActions(this);

    // StateAction
    private readonly InputActionMap m_StateAction;
    private List<IStateActionActions> m_StateActionActionsCallbackInterfaces = new List<IStateActionActions>();
    private readonly InputAction m_StateAction_Pause;
    public struct StateActionActions
    {
        private @PlayerInputs m_Wrapper;
        public StateActionActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_StateAction_Pause;
        public InputActionMap Get() { return m_Wrapper.m_StateAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StateActionActions set) { return set.Get(); }
        public void AddCallbacks(IStateActionActions instance)
        {
            if (instance == null || m_Wrapper.m_StateActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StateActionActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IStateActionActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IStateActionActions instance)
        {
            if (m_Wrapper.m_StateActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStateActionActions instance)
        {
            foreach (var item in m_Wrapper.m_StateActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StateActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StateActionActions @StateAction => new StateActionActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    public struct UIActions
    {
        private @PlayerInputs m_Wrapper;
        public UIActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface ICameraActions
    {
        void OnDelta(InputAction.CallbackContext context);
        void OnDrag(InputAction.CallbackContext context);
        void OnTurn(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
    public interface IMemberActionActions
    {
        void OnCrouch(InputAction.CallbackContext context);
        void OnDisableRun(InputAction.CallbackContext context);
        void OnEnableRun(InputAction.CallbackContext context);
    }
    public interface IStateActionActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
    }
}
